version: "3.8"
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./jobs:/opt/jobs

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    ports:
      - "8081:8081"
    volumes:
      - ./jobs:/opt/jobs

  spark-comet:
    image: apache/datafusion-comet:latest  # Replace with built/published Comet image
    container_name: spark-comet
    depends_on:
      - spark-master
      - spark-worker
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    ports:
      - "7078:7077"  # Expose Comet-enabled master
      - "8082:8080"
    volumes:
      - ./jobs:/opt/jobs
    # If needed, configure classpath for Comet plugin:
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --conf spark.plugins=org.apache.spark.CometPlugin
      --conf spark.comet.enabled=true
      --conf spark.comet.exec.enabled=true

